### ISSUE TITLE
Can we support python 3.12?

### ISSUE THREAD

**Issue by jbusecke** [xgcm/aerobulk-python#75]
3.12 does not seem to work (just stupidly created a dupe #74 and fails with 
```
Obtaining file:///home/runner/work/aerobulk-python/aerobulk-python
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/runner/work/aerobulk-python/aerobulk-python/setup.py", line 7, in <module>
          import numpy.distutils.command.sdist  # noqa
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      ModuleNotFoundError: No module named 'numpy.distutils'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```
On first glance this seems like something in numpy has changed in recent versions? This def needs some deeper investigation.

_Originally posted by @jbusecke in https://github.com/xgcm/aerobulk-python/issues/68#issuecomment-1959922051_

**Comment by jbusecke** [comment]
The failure in the conda-feedstock https://github.com/conda-forge/aerobulk-python-feedstock/pull/14 is probably related.

**Comment by jbusecke** [comment]
I just noticed that the deploy action https://github.com/xgcm/aerobulk-python/actions/runs/8008831531 also failed when using python [3.12](https://github.com/xgcm/aerobulk-python/actions/runs/8008831531/job/21876131327#step:4:6).

Some more digging suggests that we will need to migrate away from numpy.distutils (see [here](https://numpy.org/doc/stable/reference/distutils_status_migration.html)) in the future. I suspect this will be a good amount of work, and probably not time sensitive right now (for the time being pinning to python 3.11 should not block too many folks? ). Just taking notes here to facilitate picking this up later.

**Comment by jbusecke** [comment]
I rereleased 0.4.0 with #78 and that seems to work again.
